import 'styles/globals.css'

import { Inter } from 'next/font/google'

const inter = Inter({
  preload: true,
  subsets: ['latin'],
})

const interClassName = inter.className

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
